{
    "options" : {
        "javaArgs" : "", 
        "help" : "false", 
        "java" : "java", 
        "arrayIndexStates" : "false", 
        "objectStates" : "false", 
        "noInstrument" : "false", 
        "profile" : "true", 
        "arrayCacheSize" : "16", 
        "lockCacheSize" : "4", 
        "fudgeExceptionStackTraces" : "true", 
        "traces" : "false", 
        "fail" : "false", 
        "record" : "true", 
        "profileExt" : "-8-threads-prof-0.py", 
        "create" : "false", 
        "args" : "[]", 
        "quiet" : "false", 
        "d" : "[]", 
        "logs" : "log", 
        "out" : "", 
        "err" : "", 
        "instrumentFullJDK" : "false", 
        "bytecodeDump" : "false", 
        "bytecodeDumpDir" : "log/bytecode-dump", 
        "verify" : "false", 
        "preVerify" : "false", 
        "frames" : "false"
        }, 
    "threads" : 8, 
    "frequently communicating stacks" : 20, 
    "Premain time" : 19, 
    "Premain to fini time" : 2628248, 
    "Instrumentation time" : 90, 
    "Main time" : 0, 
    "Max comm. methods per module" : -2147483648, 
    "Max interface methods per module" : -2147483648, 
    "Max total methods per module" : -2147483648, 
    "All field reads" : 627629771, 
    "Communicating field reads" : 367715362, 
    "Communicating field read slow path" : 44, 
    "All array reads" : 5306626222, 
    "Communicating array reads" : 2356501374, 
    "Communicating array read slow path" : 257, 
    "All acquires" : 3, 
    "Communicating acquires" : 0, 
    "Communicating acquire slow path" : 0, 
    "Max BitVectorIntSet slots" : 1, 
    "Array hits" : 7464881640, 
    "Array misses" : 328759804, 
    "Lock hits" : 5, 
    "Lock misses" : 1, 
    "States" : 31, 
    "Distinct stacks created" : 22, 
    "Communicating stack depths" : {1 : 161, 
                                    2 : 119}, 
    "Reader stack depths (per comm. pair)" : {1 : 77, 
                                              2 : 63}, 
    "Writer stack depths (per comm. pair)" : {1 : 84, 
                                              2 : 56}, 
    "Writer stack depth - reader stack depth (per comm. pair)" : {0 : 133, 
                                                                  1 : 7}, 
    "Length in methods of stack segments" : {1 : 280}, 
    "Set size in methods of stack segments (writers only for now)" : {1 : 140}, 
    "Segments on a communicating stack" : {1 : 140}, 
    "Modules used" : 2, 
    "Full stack walks" : 141, 
    "Level 2 memo hits" : 301, 
    "Total comm nodes in used specs" : 6, 
    "Total comm edges in used specs" : 6, 
    "Total interface nodes in used specs" : 6, 
    "Total interface edges in used specs" : 0, 
    "Total comm nodes in run" : 6, 
    "Total comm edges in run" : 6, 
    "Total interface nodes in run" : 0, 
    "Total interface edges in run" : 0, 
    "Memory peak" : 44400296, 
    "Memory used" : 36411712, 
    "Memory max" : 3728277504, 
    "Compile time" : 323, 
    "GC time" : 53
}
